=== YuliiaFedchun/SOLVDLabaTaskBlock2/block2-avia-booking/src/main/resources/flight-info.xsd
<?xml version="1.0" encoding="UTF-8" ?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:complexType name="planeTypeT">
        <xs:attribute name="name" type="xs:string" use="required"/>
        <xs:attribute name="seatsNumber" type="xs:positiveInteger" use="required"/>
    </xs:complexType>

    <xs:complexType name="airportType">
        <xs:attribute name="name" type="xs:string" use="required"/>
        <xs:attribute name="city" type="xs:string" use="required"/>
        <xs:attribute name="country" type="xs:string" use="required"/>
        <xs:attribute name="typeName" type="xs:string" use="required"/>
    </xs:complexType>

    <xs:complexType name="luggageTariffType">
        <xs:attribute name="handLuggagePrice" type="xs:double" use="required"/>
        <xs:attribute name="registerLuggagePrice" type="xs:double" use="required"/>
    </xs:complexType>

    <xs:complexType name="flightTypesT">
        <xs:sequence>
            <xs:element name="flightType" type="xs:string" minOccurs="1" maxOccurs="3"/>
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="airlineType">
        <xs:all>
            <xs:element name="flightTypes" type="flightTypesT"/>
            <xs:element name="luggageTariff" type="luggageTariffType"/>
        </xs:all>
        <xs:attribute name="name" type="xs:string" use="required"/>
        <xs:attribute name="code" type="xs:string" use="required"/>
    </xs:complexType>

    <xs:complexType name="flightType">
        <xs:all>
            <xs:element name="number" type="xs:string"/>
            <xs:element name="departureTime" type="xs:string"/>
            <xs:element name="arrivalTime" type="xs:string"/>
            <xs:element name="airline" type="airlineType"/>
            <xs:element name="departureAirport" type="airportType"/>
            <xs:element name="arrivalAirport" type="airportType"/>
            <xs:element name="planeType" type="planeTypeT"/>
        </xs:all>
    </xs:complexType>

    <xs:complexType name="flightInfoType">
        <xs:all>
            <xs:element name="issueDate" type="xs:string"/>
            <xs:element name="flight" type="flightType"/>
            <xs:element name="ticketsNumber" type="xs:int"/>
        </xs:all>
    </xs:complexType>

    <xs:element name="flight-info" type="flightInfoType"/>

</xs:schema>

=== YuliiaFedchun/SOLVDLabaTaskBlock2/block2-avia-booking/src/main/resources/flight-info.xml
<flight-info xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xsi:noNamespaceSchemaLocation="flight-info.xsd">
    <issueDate>January-05-2024</issueDate>
    <flight>
        <number>0035</number>
        <departureTime>2023-12-19 12:35:00</departureTime>
        <arrivalTime>2023-12-19 13:50:00</arrivalTime>

        <airline name="KLM Royal Dutch Airlines" code="KLM">
            <flightTypes>
                <flightType>regular</flightType>
                <flightType>charter</flightType>
            </flightTypes>
            <luggageTariff handLuggagePrice="15.0" registerLuggagePrice="25.0"/>
        </airline>

        <departureAirport name="Charles de Gaulle" city="Paris" country="France" typeName="international"/>

        <arrivalAirport name="Heathrow" city="London" country="Great Britain" typeName="international"/>

        <planeType name="Boeing-737" seatsNumber="350"/>
    </flight>

    <ticketsNumber>200</ticketsNumber>

</flight-info>
